# Generated by Django 3.2.5 on 2021-08-22 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import itStock.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0007_remove_order_orderserial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('fundNumber', models.CharField(default=itStock.models.increment_booking_number, editable=False, max_length=150, primary_key=True, serialize=False)),
                ('fundName', models.CharField(max_length=150, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('SEND', 'SEND'), ('ACCEPT', 'ACCEPT'), ('DELIVER', 'DELIVER'), ('HOLD', 'HOLD'), ('REJECT', 'REJECT')], default='NEW', max_length=10, null=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fund',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNumber', models.CharField(max_length=150, null=True, unique=True)),
                ('totalAmount', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('SEND', 'SEND'), ('ACCEPT', 'ACCEPT'), ('DELIVER', 'DELIVER'), ('HOLD', 'HOLD'), ('REJECT', 'REJECT')], default='SEND', max_length=10, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierName', models.CharField(max_length=150, null=True)),
                ('contactName', models.CharField(max_length=150, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('contactNumber', models.CharField(max_length=150, null=True, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=150, null=True)),
                ('quantity', models.PositiveIntegerField(default='1', null=True)),
                ('warranty', models.CharField(choices=[('NULL', 'NULL'), ('30 D', '30 D'), ('90 D', '90 D'), ('1 Year', '1 Year'), ('2 Year', '2 Year'), ('3 Year', '3 Year'), ('Life Time', 'Life Time')], default='NULL', max_length=10, null=True)),
                ('stokStatus', models.CharField(choices=[('IN STOCK', 'IN STOCK'), ('RETURN', 'RETURN'), ('DELIVER', 'DELIVER'), ('WARRANTY CLAIM', ' WARRANTY CLAIM'), ('REJECT', 'REJECT')], default='IN STOCK', max_length=15, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
                ('invoiceNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itStock.invoice')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
                ('orderSerial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.order')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplierName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itStock.supplier'),
        ),
        migrations.CreateModel(
            name='FundDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(max_length=150, null=True)),
                ('buyer', models.CharField(max_length=150, null=True)),
                ('style', models.CharField(max_length=150, null=True)),
                ('quantity', models.CharField(max_length=150, null=True)),
                ('rate', models.CharField(max_length=150, null=True)),
                ('amount', models.CharField(max_length=150, null=True)),
                ('remarks', models.CharField(max_length=150, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('SEND', 'SEND'), ('ACCEPT', 'ACCEPT'), ('DELIVER', 'DELIVER'), ('HOLD', 'HOLD'), ('REJECT', 'REJECT')], default='NEW', max_length=10, null=True)),
                ('fundName', models.CharField(max_length=150, null=True)),
                ('fundNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funddetail', to='itStock.fund')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'funddetail',
            },
        ),
    ]
