# Generated by Django 3.2.5 on 2021-08-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funddetail',
            name='test',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
