# Generated by Django 3.2.5 on 2021-08-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0004_rename_fubdserial_funddetail_fundserial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='fundAmount',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
