# Generated by Django 3.2.5 on 2021-08-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0005_fund_fundamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funddetail',
            name='fundSerial',
            field=models.CharField(editable=False, max_length=15, null=True),
        ),
    ]
