# Generated by Django 3.2.5 on 2021-08-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0006_alter_funddetail_fundserial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='unit',
            field=models.CharField(choices=[('FSL HQT', 'FSL HQT'), ('FSL', 'FSL'), ('BRL', 'BRL')], default='FSL HQT', max_length=10, null=True),
        ),
    ]
