# Generated by Django 3.2.5 on 2021-08-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0007_fund_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='fundAmount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='funddetail',
            name='quantity',
            field=models.PositiveIntegerField(default='1', null=True),
        ),
        migrations.AlterField(
            model_name='funddetail',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
