# Generated by Django 3.2.5 on 2021-09-11 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_depthead'),
        ('itStock', '0009_auto_20210907_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.department'),
        ),
    ]
