# Generated by Django 3.2.5 on 2021-09-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0010_fund_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SEND', 'SEND'), ('ACCEPT', 'ACCEPT'), ('DELIVER', 'DELIVER'), ('WAITING', 'WAITING'), ('APPROVE', 'APPROVE'), ('HOLD', 'HOLD'), ('REJECT', 'REJECT')], default='NEW', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='funddetail',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SEND', 'SEND'), ('ACCEPT', 'ACCEPT'), ('DELIVER', 'DELIVER'), ('WAITING', 'WAITING'), ('APPROVE', 'APPROVE'), ('HOLD', 'HOLD'), ('REJECT', 'REJECT')], default='NEW', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SEND', 'SEND'), ('ACCEPT', 'ACCEPT'), ('DELIVER', 'DELIVER'), ('WAITING', 'WAITING'), ('APPROVE', 'APPROVE'), ('HOLD', 'HOLD'), ('REJECT', 'REJECT')], default='SEND', max_length=10, null=True),
        ),
    ]
