# Generated by Django 3.2.5 on 2021-09-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0011_auto_20210913_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='admindpt',
            field=models.CharField(default='NULL', max_length=150),
        ),
        migrations.AlterField(
            model_name='fund',
            name='director',
            field=models.CharField(default='NULL', max_length=150),
        ),
        migrations.AlterField(
            model_name='fund',
            name='gmacc',
            field=models.CharField(default='NULL', max_length=150),
        ),
        migrations.AlterField(
            model_name='fund',
            name='headdept',
            field=models.CharField(default='NULL', max_length=150),
        ),
        migrations.AlterField(
            model_name='fund',
            name='md',
            field=models.CharField(default='NULL', max_length=150),
        ),
    ]
