# Generated by Django 3.2.5 on 2021-09-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0014_rename_productdetail_invoicedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
