# Generated by Django 3.2.5 on 2021-09-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0015_alter_invoicedetail_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedetail',
            old_name='name',
            new_name='productname',
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='price',
            field=models.PositiveIntegerField(default='1', null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='unitprice',
            field=models.PositiveIntegerField(default='1', null=True),
        ),
    ]
