# Generated by Django 3.2.5 on 2021-09-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0016_auto_20210922_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='category',
        ),
        migrations.RemoveField(
            model_name='invoicedetail',
            name='orderSerial',
        ),
        migrations.RemoveField(
            model_name='invoicedetail',
            name='stokStatus',
        ),
    ]
