# Generated by Django 3.2.5 on 2021-09-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0018_alter_invoice_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedetail',
            old_name='productname',
            new_name='productName',
        ),
    ]
