# Generated by Django 3.2.5 on 2021-09-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0020_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoice',
            table='invoice',
        ),
        migrations.AlterModelTable(
            name='invoicedetail',
            table='invoicedetail',
        ),
    ]
