# Generated by Django 3.2.5 on 2021-09-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0021_auto_20210922_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='macaddress',
            field=models.CharField(default='NULL', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='price',
            field=models.PositiveIntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='quantity',
            field=models.PositiveIntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='unitprice',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
