# Generated by Django 3.2.5 on 2021-09-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0022_auto_20210922_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='invoiceNumber',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
