# Generated by Django 3.2.5 on 2021-09-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0023_alter_invoicedetail_invoicenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='macaddress',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='warranty',
            field=models.CharField(choices=[('NULL', 'NULL'), ('30 D', '30 D'), ('90 D', '90 D'), ('1 Year', '1 Year'), ('2 Year', '2 Year'), ('3 Year', '3 Year'), ('Life Time', 'Life Time')], max_length=10, null=True),
        ),
    ]
