# Generated by Django 3.2.5 on 2021-09-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0024_auto_20210925_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='warranty',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
