# Generated by Django 3.2.5 on 2022-01-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0025_alter_invoicedetail_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='funddetail',
            name='image',
            field=models.ImageField(default='pdefault.png', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='warranty',
            field=models.CharField(choices=[('NULL', 'NULL'), ('30 D', '30 D'), ('90 D', '90 D'), ('1 Year', '1 Year'), ('2 Year', '2 Year'), ('3 Year', '3 Year'), ('Life Time', 'Life Time')], max_length=10, null=True),
        ),
    ]
