# Generated by Django 3.2.5 on 2022-01-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0026_auto_20220105_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funddetail',
            name='image',
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='image',
            field=models.ImageField(default='pdefault.png', upload_to='profile_images'),
        ),
    ]
