# Generated by Django 3.2.5 on 2022-01-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0028_remove_invoicedetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='image',
            field=models.ImageField(default='pdefault.png', upload_to='profile_images'),
        ),
    ]
