# Generated by Django 3.2.5 on 2022-01-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0030_remove_invoicedetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='pdf',
            field=models.ImageField(default='pdefault.pdf', upload_to='invoice_pdf/'),
        ),
    ]
