# Generated by Django 3.2.5 on 2022-01-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0031_invoicedetail_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='pdf',
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(default='pdefault.pdf', upload_to='invoice_pdf/'),
        ),
    ]
