# Generated by Django 3.2.5 on 2022-01-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0033_alter_invoice_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='pdf',
        ),
    ]
