# Generated by Django 3.2.5 on 2022-01-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0041_auto_20220110_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='fundSerial',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
