# Generated by Django 3.2.5 on 2022-01-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0043_remove_invoicedetail_fundserial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funddetail',
            name='invoiceNumber',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
