# Generated by Django 3.2.5 on 2022-01-11 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0044_funddetail_invoicenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='fundSerial',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='funddetail',
            name='invoiceNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itStock.invoicedetail'),
        ),
    ]
