# Generated by Django 3.2.5 on 2022-01-11 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0045_auto_20220111_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funddetail',
            name='invoiceNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itStock.invoice'),
        ),
    ]
