# Generated by Django 3.2.5 on 2022-01-12 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0046_alter_funddetail_invoicenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='fundSerial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itStock.invoice'),
        ),
    ]
