# Generated by Django 3.2.5 on 2022-01-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0048_remove_invoicedetail_fundserial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='fundSerial',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
