# Generated by Django 3.2.5 on 2022-01-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0049_invoicedetail_fundserial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='fundSerial',
        ),
    ]
