# Generated by Django 3.2.5 on 2022-01-13 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0050_remove_invoicedetail_fundserial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
