# Generated by Django 3.2.5 on 2022-01-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0052_invoicedetail_fundserial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='unit',
            field=models.CharField(choices=[('FSL HQT', 'FSL HQT'), ('FSL', 'FSL'), ('BRL', 'BRL')], default='FSL HQT', max_length=10, null=True),
        ),
    ]
