# Generated by Django 3.2.5 on 2022-02-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0053_invoice_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='unit',
            field=models.CharField(choices=[('FSL HQT', 'FSL HQT'), ('FSL', 'FSL'), ('FPL', 'FASHION PULSE'), ('BRL', 'BRL')], default='FSL HQT', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='unit',
            field=models.CharField(choices=[('FSL HQT', 'FSL HQT'), ('FSL', 'FSL'), ('FPL', 'FASHION PULSE'), ('BRL', 'BRL')], default='FSL HQT', max_length=10, null=True),
        ),
    ]
