# Generated by Django 3.2.5 on 2022-02-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0054_auto_20220207_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='addstock',
            field=models.BooleanField(default=False),
        ),
    ]
