# Generated by Django 3.2.5 on 2022-02-07 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20220207_0607'),
        ('itStock', '0057_alter_invoicedetail_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='category',
            field=models.ForeignKey(default='30', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.category'),
        ),
    ]
