# Generated by Django 3.2.5 on 2022-02-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0061_stockissue_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='funddetail',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
