# Generated by Django 3.2.5 on 2022-02-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0062_funddetail_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funddetail',
            name='unit',
        ),
    ]
