# Generated by Django 3.2.5 on 2022-02-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0065_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='productname',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
