# Generated by Django 3.2.5 on 2022-02-15 13:53

from django.db import migrations, models
import itStock.models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0066_alter_inventory_productname'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InventoryNumber', models.CharField(default=itStock.models.increment_Inventory_number, editable=False, max_length=150)),
            ],
            options={
                'db_table': 'InventoryDetail',
            },
        ),
    ]
