# Generated by Django 3.2.5 on 2022-02-16 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0067_inventorydetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorydetail',
            old_name='InventoryNumber',
            new_name='inventoryNumber',
        ),
    ]
