# Generated by Django 3.2.5 on 2022-02-16 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itStock', '0068_rename_inventorynumber_inventorydetail_inventorynumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorydetail',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorydetail',
            name='quantity',
            field=models.PositiveIntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='inventorydetail',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorydetail',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10, null=True),
        ),
    ]
