# Generated by Django 3.2.5 on 2022-02-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0069_auto_20220216_0341'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventory',
            table='inventory',
        ),
    ]
