# Generated by Django 3.2.5 on 2022-02-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0070_alter_inventory_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventory',
            table='Inventory',
        ),
    ]
