# Generated by Django 3.2.5 on 2022-02-16 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0071_alter_inventory_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorydetail',
            name='productname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itStock.inventory'),
        ),
    ]
