# Generated by Django 3.2.5 on 2022-02-16 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0072_inventorydetail_productname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorydetail',
            old_name='productname',
            new_name='inventoryName',
        ),
    ]
