# Generated by Django 3.2.5 on 2022-02-16 04:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itStock', '0073_rename_productname_inventorydetail_inventoryname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryDetail',
            new_name='InventoryPC',
        ),
        migrations.AlterModelTable(
            name='inventorypc',
            table='InventoryPC',
        ),
    ]
