# Generated by Django 3.2.5 on 2022-02-16 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_order_orstatus'),
        ('itStock', '0075_auto_20220216_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorypc',
            name='Motherboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Motherboard', to='dashboard.category'),
        ),
    ]
