# Generated by Django 3.2.5 on 2022-02-16 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_order_orstatus'),
        ('itStock', '0076_inventorypc_motherboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorypc',
            name='GraphicsCard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GraphicsCard', to='dashboard.category'),
        ),
        migrations.AddField(
            model_name='inventorypc',
            name='Monitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Monitor', to='dashboard.category'),
        ),
        migrations.AddField(
            model_name='inventorypc',
            name='Mouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mouse', to='dashboard.category'),
        ),
        migrations.AddField(
            model_name='inventorypc',
            name='RAM',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RAM', to='dashboard.category'),
        ),
        migrations.AddField(
            model_name='inventorypc',
            name='Storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Storage', to='dashboard.category'),
        ),
        migrations.AddField(
            model_name='inventorypc',
            name='UPS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UPS', to='dashboard.category'),
        ),
    ]
