# Generated by Django 3.2.5 on 2022-02-16 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_order_orstatus'),
        ('itStock', '0078_alter_inventorypc_inventorynumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorypc',
            name='Keyboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Keyboard', to='dashboard.category'),
        ),
        migrations.AlterField(
            model_name='inventorypc',
            name='inventoryName',
            field=models.ForeignKey(default='7', null=True, on_delete=django.db.models.deletion.CASCADE, to='itStock.inventory'),
        ),
    ]
