# Generated by Django 3.2.5 on 2022-02-17 09:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0017_alter_order_orstatus'),
        ('itStock', '0079_auto_20220216_1045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryPC',
            new_name='InventoryDetail',
        ),
    ]
