# Generated by Django 3.2.5 on 2022-02-17 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_order_orstatus'),
        ('itStock', '0080_rename_inventorypc_inventorydetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorydetail',
            name='RAM',
        ),
        migrations.RemoveField(
            model_name='inventorydetail',
            name='Storage',
        ),
        migrations.AddField(
            model_name='inventorydetail',
            name='HDD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HDD', to='dashboard.category'),
        ),
        migrations.AddField(
            model_name='inventorydetail',
            name='M2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M2', to='dashboard.category'),
        ),
        migrations.AddField(
            model_name='inventorydetail',
            name='RAM1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RAM1', to='dashboard.category'),
        ),
        migrations.AddField(
            model_name='inventorydetail',
            name='RAM2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RAM2', to='dashboard.category'),
        ),
        migrations.AddField(
            model_name='inventorydetail',
            name='SSD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SSD', to='dashboard.category'),
        ),
        migrations.AlterField(
            model_name='inventorydetail',
            name='GraphicsCard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GraphicsCard', to='dashboard.category'),
        ),
        migrations.AlterField(
            model_name='inventorydetail',
            name='inventoryName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itStock.inventory'),
        ),
    ]
