# Generated by Django 3.2.5 on 2022-02-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0081_auto_20220217_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorydetail',
            old_name='SSD',
            new_name='STORAGE1',
        ),
    ]
