# Generated by Django 3.2.5 on 2022-02-19 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_order_accessoriesname'),
        ('itStock', '0082_rename_ssd_inventorydetail_storage1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorydetail',
            old_name='M2',
            new_name='STORAGE2',
        ),
        migrations.RemoveField(
            model_name='inventorydetail',
            name='HDD',
        ),
        migrations.AlterField(
            model_name='inventorydetail',
            name='RAM2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RAM2', to='dashboard.category'),
        ),
        migrations.AlterField(
            model_name='inventorydetail',
            name='STORAGE1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SSD', to='dashboard.category'),
        ),
        migrations.AlterField(
            model_name='inventorydetail',
            name='UPS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UPS', to='dashboard.category'),
        ),
        migrations.AlterModelTable(
            name='inventorydetail',
            table='InventoryDetail',
        ),
    ]
