# Generated by Django 3.2.5 on 2022-02-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0083_auto_20220219_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorydetail',
            old_name='inventoryName',
            new_name='productname',
        ),
    ]
