# Generated by Django 3.2.5 on 2022-02-19 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_order_accessoriesname'),
        ('itStock', '0084_rename_inventoryname_inventorydetail_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydetail',
            name='GraphicsCard',
            field=models.ForeignKey(blank=True, default='NULL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GraphicsCard', to='dashboard.category'),
        ),
        migrations.AlterField(
            model_name='inventorydetail',
            name='STORAGE2',
            field=models.ForeignKey(blank=True, default='NULL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M2', to='dashboard.category'),
        ),
        migrations.AlterField(
            model_name='inventorydetail',
            name='UPS',
            field=models.ForeignKey(blank=True, default='NULL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UPS', to='dashboard.category'),
        ),
    ]
