# Generated by Django 3.2.5 on 2022-02-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0087_alter_inventorydetail_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorydetail',
            name='remarks',
        ),
    ]
