# Generated by Django 3.2.5 on 2022-02-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0088_remove_inventorydetail_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorydetail',
            name='remarks',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
