# Generated by Django 3.2.5 on 2022-02-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0093_inventory_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='link',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
