# Generated by Django 3.2.5 on 2022-02-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0094_alter_inventory_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorydetail',
            name='LaptopBrand',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
