# Generated by Django 3.2.5 on 2022-02-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0095_inventorydetail_laptopbrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydetail',
            name='Laptopbag',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10, null=True),
        ),
    ]
