# Generated by Django 3.2.5 on 2022-02-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0096_alter_inventorydetail_laptopbag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydetail',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('In Stock', 'In Stock'), ('Damage', 'Damage')], default='ACTIVE', max_length=10, null=True),
        ),
    ]
