# Generated by Django 3.2.5 on 2022-02-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0097_alter_inventorydetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydetail',
            name='LaptopBrand',
            field=models.CharField(choices=[('HP', 'HP'), ('DELL', 'DELL'), ('LENOVO', 'LENOVO'), ('MAC', 'MAC'), ('ACER', 'ACER')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inventorydetail',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('IN STOCK', 'IN STOCK'), ('DAMAGE', 'DAMAGE')], default='ACTIVE', max_length=30, null=True),
        ),
    ]
