# Generated by Django 3.2.5 on 2022-02-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0098_auto_20220221_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='link',
            new_name='linkAdd',
        ),
    ]
