# Generated by Django 3.2.5 on 2022-02-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0099_rename_link_inventory_linkadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='linkDetail',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
