# Generated by Django 3.2.5 on 2022-02-21 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import itStock.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itStock', '0100_inventory_linkdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventoryNumber', models.CharField(default=itStock.models.increment_Inventory_number, editable=False, max_length=150, unique=True)),
                ('LaptopBrand', models.CharField(choices=[('HP', 'HP'), ('DELL', 'DELL'), ('LENOVO', 'LENOVO'), ('MAC', 'MAC'), ('ACER', 'ACER')], max_length=30, null=True)),
                ('remarks', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('IN STOCK', 'IN STOCK'), ('DAMAGE', 'DAMAGE')], default='ACTIVE', max_length=30, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('productname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itStock.inventory')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'InventoryAll',
            },
        ),
    ]
