# Generated by Django 3.2.5 on 2022-02-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0102_auto_20220221_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydetail',
            name='MobileBrand',
            field=models.CharField(choices=[('SAMSUNG J6', 'SAMSUNG J6'), ('SAMSUNG J7', 'SAMSUNG J6'), ('SAMSUNG J4', 'SAMSUNG J4'), ('iPHONE', 'iPHONE'), ('iPAD', 'iPAD'), ('PAD', 'PAD')], max_length=30, null=True),
        ),
    ]
