# Generated by Django 3.2.5 on 2022-02-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0103_alter_inventorydetail_mobilebrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydetail',
            name='MobileMacc',
            field=models.CharField(default='00-00-00-00', max_length=50, null=True),
        ),
    ]
