# Generated by Django 3.2.5 on 2022-02-22 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_profile_officeid'),
        ('itStock', '0106_alter_inventorydetail_mobilebrand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryall',
            old_name='LaptopBrand',
            new_name='Brand',
        ),
        migrations.RemoveField(
            model_name='inventoryall',
            name='staff',
        ),
        migrations.AddField(
            model_name='inventoryall',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.department'),
        ),
        migrations.AddField(
            model_name='inventoryall',
            name='unit',
            field=models.CharField(choices=[('FSL HQT', 'FSL HQT'), ('FSL', 'FSL'), ('FPL', 'FASHION PULSE'), ('BRL', 'BRL')], default='FSL HQT', max_length=10, null=True),
        ),
    ]
