# Generated by Django 3.2.5 on 2022-02-22 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0108_auto_20220222_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydetail',
            name='MobileBrand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itStock.mobilesetup'),
        ),
    ]
