# Generated by Django 3.2.5 on 2022-02-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0112_alter_inventoryall_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryall',
            name='macaddress',
            field=models.CharField(default='00-00-00-00', max_length=150, null=True),
        ),
    ]
