# Generated by Django 3.2.5 on 2022-02-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0113_inventoryall_macaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryall',
            name='Brand',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
