# Generated by Django 3.2.5 on 2022-02-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0114_alter_inventoryall_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryall',
            name='Brand',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryall',
            name='unit',
            field=models.CharField(blank=True, choices=[('FSL HQT', 'FSL HQT'), ('FSL', 'FSL'), ('FPL', 'FASHION PULSE'), ('BRL', 'BRL')], default='FSL HQT', max_length=10, null=True),
        ),
    ]
