# Generated by Django 3.2.5 on 2022-02-22 05:51

from django.db import migrations, models
import itStock.models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0115_auto_20220222_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryall',
            name='Brand',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryall',
            name='ExtensionNumber',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryall',
            name='inventoryNumber',
            field=models.CharField(default=itStock.models.increment_InventoryAll_number, editable=False, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryall',
            name='unit',
            field=models.CharField(choices=[('FSL HQT', 'FSL HQT'), ('FSL', 'FSL'), ('FPL', 'FASHION PULSE'), ('BRL', 'BRL')], default='FSL HQT', max_length=10, null=True),
        ),
    ]
