# Generated by Django 3.2.5 on 2022-02-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0116_auto_20220222_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryall',
            name='Brand',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
