# Generated by Django 3.2.5 on 2022-02-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0117_alter_inventoryall_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryall',
            name='Brand',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryall',
            name='ExtensionNumber',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
