# Generated by Django 3.2.5 on 2022-02-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0118_auto_20220222_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryall',
            name='model',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
