# Generated by Django 3.2.5 on 2022-08-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itStock', '0119_inventoryall_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='warranty',
            field=models.CharField(choices=[('NULL', 'NULL'), ('30 D', '30 D'), ('60 D', '60 D'), ('90 D', '90 D'), ('1 Year', '1 Year'), ('2 Year', '2 Year'), ('3 Year', '3 Year'), ('5 Year', '5 Year'), ('Life Time', 'Life Time')], default='NULL', max_length=10, null=True),
        ),
    ]
