# Generated by Django 3.2.5 on 2021-07-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='OrStatus',
            field=models.CharField(choices=[('ACCEPT', 'ACCEPT'), ('DELIVER', 'DELIVER'), ('HOLD', 'HOLD')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], max_length=10, null=True),
        ),
    ]
