# Generated by Django 3.2.5 on 2021-07-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210727_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrStatus',
            field=models.CharField(choices=[('ACCEPT', 'ACCEPT'), ('DELIVER', 'DELIVER'), ('HOLD', 'HOLD')], default='ACCEPT', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10, null=True),
        ),
    ]
