# Generated by Django 3.2.5 on 2021-07-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210727_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrStatus',
            field=models.CharField(choices=[('SEND', 'SEND'), ('ACCEPT', 'ACCEPT'), ('DELIVER', 'DELIVER'), ('HOLD', 'HOLD'), ('REJECT', 'REJECT')], default='SEND', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
