# Generated by Django 3.2.5 on 2021-07-29 06:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderSerial',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
