# Generated by Django 3.2.5 on 2021-08-09 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_order_orderserial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderSerial',
        ),
    ]
