# Generated by Django 3.2.5 on 2022-02-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20220207_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='quantity',
            new_name='damage_quantity',
        ),
        migrations.AddField(
            model_name='category',
            name='stock_quantity',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='category',
            name='total_quantity',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='category',
            name='use_quantity',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
