# Generated by Django 3.2.5 on 2022-02-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20220214_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='re_other',
            field=models.BooleanField(default=False),
        ),
    ]
