# Generated by Django 3.2.5 on 2022-02-14 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_order_re_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='re_other',
        ),
    ]
