# Generated by Django 3.2.5 on 2022-02-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_order_re_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrStatus',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SEND', 'SEND'), ('ACCEPT', 'ACCEPT'), ('DELIVER', 'DELIVER'), ('HOLD', 'HOLD'), ('REJECT', 'REJECT')], default='NEW', max_length=10, null=True),
        ),
    ]
