# Generated by Django 3.2.5 on 2022-02-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_order_orstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccessoriesName', models.CharField(max_length=150, null=True, unique=True)),
                ('Status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('STOCK', 'STOCK'), ('DAMAGE', 'DAMAGE')], default='ACTIVE', max_length=10, null=True)),
            ],
        ),
    ]
