# Generated by Django 3.2.5 on 2022-02-18 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_accessoriesgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='accGrouP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.accessoriesgroup'),
        ),
    ]
