# Generated by Django 3.2.5 on 2022-02-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_category_accgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='accGrouP',
            new_name='AGroupName',
        ),
    ]
