# Generated by Django 3.2.5 on 2022-02-19 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_rename_accgroup_category_agroupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='AccessoriesName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.accessoriesgroup'),
        ),
    ]
