# Generated by Django 3.2.5 on 2021-09-09 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dptName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeptHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dptHeadName', models.CharField(max_length=50)),
                ('boss', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.department')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('officeID', models.CharField(max_length=20)),
                ('officeLocation', models.CharField(choices=[('HQT FSL', 'HQT FSL'), ('BRL', 'BRL'), ('FSL', 'FSL')], max_length=10, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(default='default.png', upload_to='profile_images')),
                ('signature', models.ImageField(default='default.png', upload_to='signature_images')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.department')),
                ('dptHeadName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.depthead')),
                ('loginuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('utype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usertype')),
            ],
        ),
    ]
