# Generated by Django 3.2.5 on 2022-02-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210913_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='officeLocation',
            field=models.CharField(choices=[('HQT FSL', 'HQT FSL'), ('BRL', 'BRL'), ('FSL', 'FSL'), ('FPL', 'FPL')], max_length=10, null=True),
        ),
    ]
