# Generated by Django 3.2.5 on 2022-02-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_officelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='officeID',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
