# Generated by Django 3.2.5 on 2022-03-03 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fslplan.fslplan_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'Buyer',
            },
        ),
        migrations.CreateModel(
            name='ProLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'ProLine',
            },
        ),
        migrations.CreateModel(
            name='SetupLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayID', models.CharField(max_length=150, null=True)),
                ('LineWIP', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('Manpower', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_8_9', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_9_10', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_10_11', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_11_12', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_12_13', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_14_15', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_15_16', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_16_17', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_17_18', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_18_19', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_19_20', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_20_21', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_21_22', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('DataLock', models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=2, null=True)),
                ('date', models.DateField(default='YYYY-MM-DD')),
            ],
            options={
                'db_table': 'SetupLine',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'Unit',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('StyleSMV', models.CharField(blank=True, max_length=5, null=True)),
                ('DataLock', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=2, null=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fslplan.buyer')),
            ],
            options={
                'db_table': 'Style',
            },
        ),
        migrations.CreateModel(
            name='SetupDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayID', models.CharField(default=fslplan.fslplan_models.increment_booking_number, editable=False, max_length=150)),
                ('deleveryDate', models.DateField(default='YYYY-MM-DD')),
                ('INputDate', models.DateField(default='YYYY-MM-DD')),
                ('sewingEndDate', models.DateField(default='YYYY-MM-DD')),
                ('orderQty', models.PositiveSmallIntegerField(default=0)),
                ('planQtyExtra', models.PositiveSmallIntegerField(default=0)),
                ('linePlanQty', models.PositiveSmallIntegerField(default=0)),
                ('DayTerget', models.PositiveSmallIntegerField(default=0)),
                ('HourTerget', models.PositiveSmallIntegerField(default=0)),
                ('WorkHour', models.PositiveSmallIntegerField(default=10)),
                ('EstimateWorkDay', models.PositiveSmallIntegerField(default=0)),
                ('remainingWorkDay', models.PositiveSmallIntegerField(default=0)),
                ('date', models.DateField(default='YYYY-MM-DD')),
                ('loadMinutes', models.PositiveSmallIntegerField(default=0)),
                ('DataLock', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=2, null=True)),
                ('LineNum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fslplan.proline')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fslplan.buyer')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fslplan.style')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fslplan.unit')),
            ],
            options={
                'db_table': 'SetupDay',
            },
        ),
        migrations.AddField(
            model_name='proline',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fslplan.unit'),
        ),
    ]
